name: korun
description: Gestionnaire de fichiers double panneau à aperçus réels (Linux & Windows).
publish_to: 'none'
version: 0.6.8+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  sqflite_common_ffi: ^2.3.3
  watcher: ^1.1.0
  audioplayers: ^6.0.0
  file_picker: ^8.0.0
  crypto: ^3.0.3
  win32: ^5.5.0
  ffi: ^2.1.0
  mime: ^1.0.5
  pdfrx: 1.0.90
  archive: ^3.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
