name: korun
description: "Körün — Modern Cross-Platform Dual-Pane File Manager"
publish_to: 'none'
version: 0.3.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  path_provider: ^2.1.1
  path: ^1.8.3
  file_picker: ^6.1.1
  pdfx: ^2.6.0
  intl: ^0.18.1
  http: ^1.1.0
  url_launcher: ^6.1.14
  desktop_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
