import 'package:flutter/widgets.dart';

class L10n {
  static const List<Locale> supported = [
    Locale('fr'), Locale('en'), Locale('pt'), Locale('es'), Locale('ar'),
    Locale('tr'), Locale('az'), Locale('uz'), Locale('kk'),
    Locale('tk'), Locale('ky'), Locale('tt'),
  ];
  static const Map<String, String> nativeNames = {
    'fr': 'Français', 'en': 'English', 'pt': 'Português', 'es': 'Español',
    'ar': 'العربية', 'tr': 'Türkçe', 'az': 'Azərbaycanca', 'uz': 'Oʻzbekcha',
    'kk': 'Qazaqşa', 'tk': 'Türkmençe', 'ky': 'Qırğızça', 'tt': 'Tatarça',
  };
  static const Map<String, Map<String, String>> _values = {
    'fr': {'title': 'Körün — Gestionnaire de fichiers', 'select_file': 'Sélectionnez un fichier pour afficher l\'aperçu', 'details': 'Détails du fichier', 'name': 'Nom :', 'path': 'Chemin :', 'size': 'Taille :', 'modified': 'Modifié :', 'accessed': 'Accédé :', 'created': 'Créé :', 'left_panel': 'Panneau gauche', 'right_panel': 'Panneau droit', 'preview': 'Aperçu', 'show_hidden': 'Afficher les fichiers cachés', 'hide_hidden': 'Masquer les fichiers cachés', 'settings': 'Paramètres', 'theme': 'Thème', 'language': 'Langue', 'empty': 'Dossier vide', 'type': 'Type :', 'edit_dates': 'Modifier les dates', 'save': 'Enregistrer', 'cancel': 'Annuler', 'about': 'À propos', 'version': 'Version', 'author': 'Auteur', 'disclaimer': 'Fourni tel quel, sans aucune garantie.', 'auto_update': 'Mise à jour automatique et silencieuse', 'check_update': 'Vérifier les mises à jour', 'update_found': 'Mise à jour disponible', 'theme_title': 'Thèmes', 'mode_light': 'Clair', 'mode_dark': 'Sombre', 'mode_oled': 'Noir OLED', 'custom_themes': 'Thèmes personnalisés', 'theme_name': 'Nom du thème', 'create': 'Créer', 'delete': 'Supprimer', 'otken_title': 'Ötken — Historique des versions', 'no_snapshots': 'Aucun snapshot détecté', 'office_wait': 'Conversion LibreOffice…', 'office_missing': 'LibreOffice absent : aperçu indisponible', 'language_title': 'Langue', 'created_note': 'Non modifiable sous Linux (limitation du noyau). Modifiable sous Windows.', 'open': 'Ouvrir', 'copy': 'Copier', 'cut': 'Couper', 'paste': 'Coller', 'rename': 'Renommer', 'batch_rename': 'Renommage groupé', 'properties': 'Propriétés', 'new_folder': 'Nouveau dossier', 'confirm_delete': 'Confirmer la suppression', 'confirm_delete_msg': 'Voulez-vous vraiment supprimer cet élément ?', 'folder_name': 'Nom du dossier', 'sort_name': 'Nom', 'sort_size': 'Taille', 'sort_date': 'Date', 'refresh': 'Rafraîchir', 'batch_mode_number': 'Numérotation (base + numéro)', 'batch_mode_replace': 'Rechercher / remplacer', 'batch_mode_case': 'Casse (minuscules / majuscules)', 'batch_base': 'Base du nom', 'batch_start': 'Numéro de départ', 'batch_search': 'Rechercher', 'batch_replace': 'Remplacer par', 'batch_lower': 'minuscules', 'batch_upper': 'MAJUSCULES', 'batch_preview': 'Aperçu des nouveaux noms'},
    'en': {'title': 'Körün — File Manager', 'select_file': 'Select a file to preview', 'details': 'File details', 'name': 'Name:', 'path': 'Path:', 'size': 'Size:', 'modified': 'Modified:', 'accessed': 'Accessed:', 'created': 'Created:', 'left_panel': 'Left panel', 'right_panel': 'Right panel', 'preview': 'Preview', 'show_hidden': 'Show hidden files', 'hide_hidden': 'Hide hidden files', 'settings': 'Settings', 'theme': 'Theme', 'language': 'Language', 'empty': 'Empty folder', 'type': 'Type:', 'edit_dates': 'Edit dates', 'save': 'Save', 'cancel': 'Cancel', 'about': 'About', 'version': 'Version', 'author': 'Author', 'disclaimer': 'Provided as is, without any warranty.', 'auto_update': 'Silent auto-update', 'check_update': 'Check for updates', 'update_found': 'Update available', 'theme_title': 'Themes', 'mode_light': 'Light', 'mode_dark': 'Dark', 'mode_oled': 'OLED black', 'custom_themes': 'Custom themes', 'theme_name': 'Theme name', 'create': 'Create', 'delete': 'Delete', 'otken_title': 'Ötken — Version history', 'no_snapshots': 'No snapshots detected', 'office_wait': 'LibreOffice conversion…', 'office_missing': 'LibreOffice missing: preview unavailable', 'language_title': 'Language', 'created_note': 'Not settable on Linux (kernel limitation). Editable on Windows.', 'open': 'Open', 'copy': 'Copy', 'cut': 'Cut', 'paste': 'Paste', 'rename': 'Rename', 'batch_rename': 'Batch rename', 'properties': 'Properties', 'new_folder': 'New folder', 'confirm_delete': 'Confirm deletion', 'confirm_delete_msg': 'Are you sure you want to delete this item?', 'folder_name': 'Folder name', 'sort_name': 'Name', 'sort_size': 'Size', 'sort_date': 'Date', 'refresh': 'Refresh', 'batch_mode_number': 'Numbering (base + number)', 'batch_mode_replace': 'Find / replace', 'batch_mode_case': 'Case (lower / upper)', 'batch_base': 'Base name', 'batch_start': 'Start number', 'batch_search': 'Find', 'batch_replace': 'Replace with', 'batch_lower': 'lowercase', 'batch_upper': 'UPPERCASE', 'batch_preview': 'Preview of new names'},
    'pt': {'title': 'Körün — Gestor de ficheiros', 'select_file': 'Selecione um ficheiro para pré-visualizar', 'details': 'Detalhes do ficheiro', 'name': 'Nome:', 'path': 'Caminho:', 'size': 'Tamanho:', 'modified': 'Modificado:', 'accessed': 'Acedido:', 'created': 'Criado:', 'left_panel': 'Painel esquerdo', 'right_panel': 'Painel direito', 'preview': 'Pré-visualização', 'show_hidden': 'Mostrar ficheiros ocultos', 'hide_hidden': 'Ocultar ficheiros ocultos', 'settings': 'Definições', 'theme': 'Tema', 'language': 'Idioma', 'empty': 'Pasta vazia', 'type': 'Tipo:', 'edit_dates': 'Editar datas', 'save': 'Guardar', 'cancel': 'Cancelar', 'about': 'Sobre', 'version': 'Versão', 'author': 'Autor', 'disclaimer': 'Fornecido tal como está, sem qualquer garantia.', 'auto_update': 'Atualização automática silenciosa', 'check_update': 'Verificar atualizações', 'update_found': 'Atualização disponível', 'theme_title': 'Temas', 'mode_light': 'Claro', 'mode_dark': 'Escuro', 'mode_oled': 'Preto OLED', 'custom_themes': 'Temas personalizados', 'theme_name': 'Nome do tema', 'create': 'Criar', 'delete': 'Eliminar', 'otken_title': 'Ötken — Histórico de versões', 'no_snapshots': 'Nenhum snapshot detetado', 'office_wait': 'Conversão LibreOffice…', 'office_missing': 'LibreOffice ausente: pré-visualização indisponível', 'language_title': 'Idioma', 'created_note': 'Não definível no Linux (limitação do kernel). Editável no Windows.', 'open': 'Abrir', 'copy': 'Copiar', 'cut': 'Cortar', 'paste': 'Colar', 'rename': 'Renomear', 'batch_rename': 'Renomeação em lote', 'properties': 'Propriedades', 'new_folder': 'Nova pasta', 'confirm_delete': 'Confirmar eliminação', 'confirm_delete_msg': 'Tem a certeza de que quer eliminar este item?', 'folder_name': 'Nome da pasta', 'sort_name': 'Nome', 'sort_size': 'Tamanho', 'sort_date': 'Data', 'refresh': 'Atualizar', 'batch_mode_number': 'Numeração (base + número)', 'batch_mode_replace': 'Procurar / substituir', 'batch_mode_case': 'Caixa (minúsculas / maiúsculas)', 'batch_base': 'Nome base', 'batch_start': 'Número inicial', 'batch_search': 'Procurar', 'batch_replace': 'Substituir por', 'batch_lower': 'minúsculas', 'batch_upper': 'MAIÚSCULAS', 'batch_preview': 'Pré-visualização dos novos nomes'},
    'es': {'title': 'Körün — Gestor de archivos', 'select_file': 'Seleccione un archivo para previsualizar', 'details': 'Detalles del archivo', 'name': 'Nombre:', 'path': 'Ruta:', 'size': 'Tamaño:', 'modified': 'Modificado:', 'accessed': 'Accedido:', 'created': 'Creado:', 'left_panel': 'Panel izquierdo', 'right_panel': 'Panel derecho', 'preview': 'Vista previa', 'show_hidden': 'Mostrar archivos ocultos', 'hide_hidden': 'Ocultar archivos ocultos', 'settings': 'Ajustes', 'theme': 'Tema', 'language': 'Idioma', 'empty': 'Carpeta vacía', 'type': 'Tipo:', 'edit_dates': 'Editar fechas', 'save': 'Guardar', 'cancel': 'Cancelar', 'about': 'Acerca de', 'version': 'Versión', 'author': 'Autor', 'disclaimer': 'Se proporciona tal cual, sin ninguna garantía.', 'auto_update': 'Actualización automática silenciosa', 'check_update': 'Comprobar actualizaciones', 'update_found': 'Actualización disponible', 'theme_title': 'Temas', 'mode_light': 'Claro', 'mode_dark': 'Oscuro', 'mode_oled': 'Negro OLED', 'custom_themes': 'Temas personalizados', 'theme_name': 'Nombre del tema', 'create': 'Crear', 'delete': 'Eliminar', 'otken_title': 'Ötken — Historial de versiones', 'no_snapshots': 'Ningún snapshot detectado', 'office_wait': 'Conversión LibreOffice…', 'office_missing': 'LibreOffice ausente: vista previa no disponible', 'language_title': 'Idioma', 'created_note': 'No se puede cambiar en Linux (limitación del núcleo). Editable en Windows.', 'open': 'Abrir', 'copy': 'Copiar', 'cut': 'Cortar', 'paste': 'Pegar', 'rename': 'Renombrar', 'batch_rename': 'Renombrado por lotes', 'properties': 'Propiedades', 'new_folder': 'Nueva carpeta', 'confirm_delete': 'Confirmar eliminación', 'confirm_delete_msg': '¿Seguro que quieres eliminar este elemento?', 'folder_name': 'Nombre de la carpeta', 'sort_name': 'Nombre', 'sort_size': 'Tamaño', 'sort_date': 'Fecha', 'refresh': 'Actualizar', 'batch_mode_number': 'Numeración (base + número)', 'batch_mode_replace': 'Buscar / reemplazar', 'batch_mode_case': 'Mayúsculas/minúsculas', 'batch_base': 'Nombre base', 'batch_start': 'Número inicial', 'batch_search': 'Buscar', 'batch_replace': 'Reemplazar con', 'batch_lower': 'minúsculas', 'batch_upper': 'MAYÚSCULAS', 'batch_preview': 'Vista previa de los nuevos nombres'},
    'ar': {'title': 'Körün — مدير الملفات', 'select_file': 'حدد ملفًا للمعاينة', 'details': 'تفاصيل الملف', 'name': 'الاسم:', 'path': 'المسار:', 'size': 'الحجم:', 'modified': 'التعديل:', 'accessed': 'الوصول:', 'created': 'الإنشاء:', 'left_panel': 'اللوحة اليسرى', 'right_panel': 'اللوحة اليمنى', 'preview': 'معاينة', 'show_hidden': 'إظهار الملفات المخفية', 'hide_hidden': 'إخفاء الملفات المخفية', 'settings': 'الإعدادات', 'theme': 'السمة', 'language': 'اللغة', 'empty': 'مجلد فارغ', 'type': 'النوع:', 'edit_dates': 'تعديل التواريخ', 'save': 'حفظ', 'cancel': 'إلغاء', 'about': 'حول', 'version': 'الإصدار', 'author': 'المؤلف', 'disclaimer': 'يُقدم كما هو، دون أي ضمان.', 'auto_update': 'تحديث تلقائي صامت', 'check_update': 'التحقق من التحديثات', 'update_found': 'تحديث متوفر', 'theme_title': 'السمات', 'mode_light': 'فاتح', 'mode_dark': 'داكن', 'mode_oled': 'أسود OLED', 'custom_themes': 'سمات مخصصة', 'theme_name': 'اسم السمة', 'create': 'إنشاء', 'delete': 'حذف', 'otken_title': 'Ötken — سجل الإصدارات', 'no_snapshots': 'لا توجد لقطات', 'office_wait': 'تحويل LibreOffice…', 'office_missing': 'LibreOffice غير موجود: المعاينة غير متاحة', 'language_title': 'اللغة', 'created_note': 'لا يمكن تعديلها في لينكس (قيد في النواة). قابلة للتعديل في ويندوز.', 'open': 'فتح', 'copy': 'نسخ', 'cut': 'قص', 'paste': 'لصق', 'rename': 'إعادة تسمية', 'batch_rename': 'إعادة تسمية جماعية', 'properties': 'خصائص', 'new_folder': 'مجلد جديد', 'confirm_delete': 'تأكيد الحذف', 'confirm_delete_msg': 'هل تريد حقًا حذف هذا العنصر؟', 'folder_name': 'اسم المجلد', 'sort_name': 'الاسم', 'sort_size': 'الحجم', 'sort_date': 'التاريخ', 'refresh': 'تحديث', 'batch_mode_number': 'ترقيم (أساس + رقم)', 'batch_mode_replace': 'بحث / استبدال', 'batch_mode_case': 'حالة الأحرف (صغير / كبير)', 'batch_base': 'الاسم الأساسي', 'batch_start': 'رقم البداية', 'batch_search': 'بحث', 'batch_replace': 'استبدال بـ', 'batch_lower': 'أحرف صغيرة', 'batch_upper': 'أحرف كبيرة', 'batch_preview': 'معاينة الأسماء الجديدة'},
    'tr': {'title': 'Körün — Dosya Yöneticisi', 'select_file': 'Önizleme için bir dosya seçin', 'details': 'Dosya detayları', 'name': 'Ad:', 'path': 'Yol:', 'size': 'Boyut:', 'modified': 'Değiştirilme:', 'accessed': 'Erişilme:', 'created': 'Oluşturma:', 'left_panel': 'Sol panel', 'right_panel': 'Sağ panel', 'preview': 'Önizleme', 'show_hidden': 'Gizli dosyaları göster', 'hide_hidden': 'Gizli dosyaları gizle', 'settings': 'Ayarlar', 'theme': 'Tema', 'language': 'Dil', 'empty': 'Boş klasör', 'type': 'Tür:', 'edit_dates': 'Tarihleri düzenle', 'save': 'Kaydet', 'cancel': 'İptal', 'about': 'Hakkında', 'version': 'Sürüm', 'author': 'Yazar', 'disclaimer': 'Olduğu gibi sağlanır, hiçbir garanti olmadan.', 'auto_update': 'Sessiz otomatik güncelleme', 'check_update': 'Güncellemeleri denetle', 'update_found': 'Güncelleme mevcut', 'theme_title': 'Temalar', 'mode_light': 'Açık', 'mode_dark': 'Karanlık', 'mode_oled': 'OLED siyah', 'custom_themes': 'Özel temalar', 'theme_name': 'Tema adı', 'create': 'Oluştur', 'delete': 'Sil', 'otken_title': 'Ötken — Sürüm geçmişi', 'no_snapshots': 'Snapshot bulunamadı', 'office_wait': 'LibreOffice dönüşümü…', 'office_missing': 'LibreOffice yok: önizleme yok', 'language_title': 'Dil', 'created_note': 'Linux’ta ayarlanamaz (çekirdek kısıtlaması). Windows’ta düzenlenebilir.', 'open': 'Aç', 'copy': 'Kopyala', 'cut': 'Kes', 'paste': 'Yapıştır', 'rename': 'Yeniden adlandır', 'batch_rename': 'Toplu yeniden adlandırma', 'properties': 'Özellikler', 'new_folder': 'Yeni klasör', 'confirm_delete': 'Silmeyi onayla', 'confirm_delete_msg': 'Bu öğeyi gerçekten silmek istiyor musunuz?', 'folder_name': 'Klasör adı', 'sort_name': 'Ad', 'sort_size': 'Boyut', 'sort_date': 'Tarih', 'refresh': 'Yenile', 'batch_mode_number': 'Numaralandırma (taban + numara)', 'batch_mode_replace': 'Bul / değiştir', 'batch_mode_case': 'Büyük-küçük harf', 'batch_base': 'Taban ad', 'batch_start': 'Başlangıç numarası', 'batch_search': 'Bul', 'batch_replace': 'Değiştir', 'batch_lower': 'küçük harf', 'batch_upper': 'BÜYÜK HARF', 'batch_preview': 'Yeni adların önizlemesi'},
    'az': {'title': 'Körün — Fayl İdarəedicisi', 'select_file': 'Baxış üçün fayl seçin', 'details': 'Fayl təfərrüatları', 'name': 'Ad:', 'path': 'Yol:', 'size': 'Ölçü:', 'modified': 'Dəyişdirildi:', 'accessed': 'Müraciət:', 'created': 'Yaradıldı:', 'left_panel': 'Sol panel', 'right_panel': 'Sağ panel', 'preview': 'Baxış', 'show_hidden': 'Gizli faylları göstər', 'hide_hidden': 'Gizli faylları gizlət', 'settings': 'Parametrlər', 'theme': 'Mövzu', 'language': 'Dil', 'empty': 'Boş qovluq', 'type': 'Növ:', 'edit_dates': 'Tarixləri redaktə et', 'save': 'Yadda saxla', 'cancel': 'Ləğv et', 'about': 'Haqqında', 'version': 'Versiya', 'author': 'Müəllif', 'disclaimer': 'Olduğu kimi təqdim olunur, heç bir zəmanət yoxdur.', 'auto_update': 'Səssiz avtomatik yenilənmə', 'check_update': 'Yenilənmələri yoxla', 'update_found': 'Yenilənmə mövcuddur', 'theme_title': 'Temalar', 'mode_light': 'Açıq', 'mode_dark': 'Tünd', 'mode_oled': 'OLED qara', 'custom_themes': 'Xüsusi temalar', 'theme_name': 'Tema adı', 'create': 'Yarat', 'delete': 'Sil', 'otken_title': 'Ötken — Versiya tarixçəsi', 'no_snapshots': 'Snapshot tapılmadı', 'office_wait': 'LibreOffice çevirməsi…', 'office_missing': 'LibreOffice yoxdur: baxış yoxdur', 'language_title': 'Dil', 'created_note': 'Linux-da təyin edilə bilməz (nüvə məhdudiyyəti). Windows-da redaktə olunur.', 'open': 'Aç', 'copy': 'Kopyala', 'cut': 'Kəs', 'paste': 'Yapışdır', 'rename': 'Adını dəyiş', 'batch_rename': 'Kütləvi ad dəyişmə', 'properties': 'Xüsusiyyətlər', 'new_folder': 'Yeni qovluq', 'confirm_delete': 'Silməni təsdiqlə', 'confirm_delete_msg': 'Bu elementi həqiqətən silmək istəyirsiniz?', 'folder_name': 'Qovluq adı', 'sort_name': 'Ad', 'sort_size': 'Ölçü', 'sort_date': 'Tarix', 'refresh': 'Yenilə', 'batch_mode_number': 'Nömrələmə (bazan + nömrə)', 'batch_mode_replace': 'Tap / dəyiş', 'batch_mode_case': 'Hərf ölçüsü', 'batch_base': 'Baza ad', 'batch_start': 'Başlanğıc nömrəsi', 'batch_search': 'Tap', 'batch_replace': 'Əvəz et', 'batch_lower': 'kiçik hərflər', 'batch_upper': 'BÖYÜK HƏRFLƏR', 'batch_preview': 'Yeni adların önizləməsi'},
    'uz': {'title': 'Körün — Fayl menejeri', 'select_file': 'Koʻrib chiqish uchun fayl tanlang', 'details': 'Fayl tafsilotlari', 'name': 'Nomi:', 'path': 'Yoʻl:', 'size': 'Hajmi:', 'modified': 'Oʻzgartirilgan:', 'accessed': 'Kirilgan:', 'created': 'Yaratilgan:', 'left_panel': 'Chap panel', 'right_panel': 'Oʻng panel', 'preview': 'Koʻrib chiqish', 'show_hidden': 'Yashirin fayllarni koʻrsatish', 'hide_hidden': 'Yashirin fayllarni yashirish', 'settings': 'Sozlamalar', 'theme': 'Mavzu', 'language': 'Til', 'empty': 'Boʻsh jild', 'type': 'Turi:', 'edit_dates': 'Sanalarni tahrirlash', 'save': 'Saqlash', 'cancel': 'Bekor qilish', 'about': 'Haqida', 'version': 'Versiya', 'author': 'Muallif', 'disclaimer': 'Qanday boʻlsa shunday taqdim etiladi, kafolat yoʻq.', 'auto_update': 'Sessiz avto yangilash', 'check_update': 'Yangilanishlarni tekshirish', 'update_found': 'Yangilanish mavjud', 'theme_title': 'Mavzular', 'mode_light': 'Yorugʻ', 'mode_dark': 'Toʻq', 'mode_oled': 'OLED qora', 'custom_themes': 'Maxsus mavzular', 'theme_name': 'Mavzu nomi', 'create': 'Yaratish', 'delete': 'Oʻchirish', 'otken_title': 'Ötken — Versiyalar tarixi', 'no_snapshots': 'Snapshot topilmadi', 'office_wait': 'LibreOffice konvertatsiyasi…', 'office_missing': 'LibreOffice yoʻq: koʻrib chiqish yoʻq', 'language_title': 'Til', 'created_note': 'Linux-da oʻrnatib boʻlmaydi (yadro cheklovi). Windows-da tahrirlanadi.', 'open': 'Ochish', 'copy': 'Nusxalash', 'cut': 'Kesish', 'paste': 'Qoʻyish', 'rename': 'Qayta nomlash', 'batch_rename': 'Guruhli qayta nomlash', 'properties': 'Xususiyatlar', 'new_folder': 'Yangi jild', 'confirm_delete': 'Oʻchirishni tasdiqlash', 'confirm_delete_msg': 'Bu elementni rostdan oʻchirmoqchimisiz?', 'folder_name': 'Jild nomi', 'sort_name': 'Nom', 'sort_size': 'Hajm', 'sort_date': 'Sana', 'refresh': 'Yangilash', 'batch_mode_number': 'Raqamlash (asos + raqam)', 'batch_mode_replace': 'Topish / almashtirish', 'batch_mode_case': 'Harf holati', 'batch_base': 'Asos nom', 'batch_start': 'Boshlangʻich raqam', 'batch_search': 'Topish', 'batch_replace': 'Almashtirish', 'batch_lower': 'kichik harflar', 'batch_upper': 'KATTA HARFLAR', 'batch_preview': 'Yangi nomlar koʻrinishi'},
    'kk': {'title': 'Körün — Файл менеджері', 'select_file': 'Алдын ала қарау үшін файл таңдаңыз', 'details': 'Файл мәліметтері', 'name': 'Аты:', 'path': 'Жол:', 'size': 'Өлшемі:', 'modified': 'Өзгертілген:', 'accessed': 'Қатыналған:', 'created': 'Жасалған:', 'left_panel': 'Сол панель', 'right_panel': 'Оң панель', 'preview': 'Алдын ала қарау', 'show_hidden': 'Жасырын файлдарды көрсету', 'hide_hidden': 'Жасырын файлдарды жасыру', 'settings': 'Параметрлер', 'theme': 'Тақырып', 'language': 'Тіл', 'empty': 'Бос қалта', 'type': 'Түрі:', 'edit_dates': 'Күндерді өңдеу', 'save': 'Сақтау', 'cancel': 'Болдырмау', 'about': 'Туралы', 'version': 'Нұсқа', 'author': 'Автор', 'disclaimer': 'Қалай болса солай беріледі, кепілдік жоқ.', 'auto_update': 'Үнсіз авто жаңарту', 'check_update': 'Жаңартуларды тексеру', 'update_found': 'Жаңарту бар', 'theme_title': 'Темалар', 'mode_light': 'Жарық', 'mode_dark': 'Қараңғы', 'mode_oled': 'OLED қара', 'custom_themes': 'Арнаулы темалар', 'theme_name': 'Тема атауы', 'create': 'Жасау', 'delete': 'Жою', 'otken_title': 'Ötken — Нұсқалар тарихы', 'no_snapshots': 'Snapshot табылмады', 'office_wait': 'LibreOffice түрлендіруі…', 'office_missing': 'LibreOffice жоқ: алдын ала қарау жоқ', 'language_title': 'Тіл', 'created_note': 'Linux-та орнатылмайды (ядро шектеуі). Windows-та өңделеді.', 'open': 'Ашу', 'copy': 'Көшіру', 'cut': 'Қиып алу', 'paste': 'Қою', 'rename': 'Атын өзгерту', 'batch_rename': 'Жаппай атауын өзгерту', 'properties': 'Қасиеттері', 'new_folder': 'Жаңа қалта', 'confirm_delete': 'Жоюды растау', 'confirm_delete_msg': 'Бұл элементті шынымен жойғыңыз келе ме?', 'folder_name': 'Қалта атауы', 'sort_name': 'Атау', 'sort_size': 'Өлшем', 'sort_date': 'Күні', 'refresh': 'Жаңарту', 'batch_mode_number': 'Нөмірлеу (негіз + нөмір)', 'batch_mode_replace': 'Табу / ауыстыру', 'batch_mode_case': 'Әріп өлшемі', 'batch_base': 'Негіз атау', 'batch_start': 'Бастапқы нөмір', 'batch_search': 'Табу', 'batch_replace': 'Ауыстыру', 'batch_lower': 'кіші әріптер', 'batch_upper': 'БАС ӘРІПТЕР', 'batch_preview': 'Жаңа атауларды алдын ала қарау'},
    'tk': {'title': 'Körün — Faýl dolandyryjysy', 'select_file': 'Synlamak üçin faýl saýlaň', 'details': 'Faýl jikme-jikleri', 'name': 'Ady:', 'path': 'Ýoly:', 'size': 'Möçberi:', 'modified': 'Üýtgedilen:', 'accessed': 'Elýeterli:', 'created': 'Döredilen:', 'left_panel': 'Sol panel', 'right_panel': 'Sag panel', 'preview': 'Syn', 'show_hidden': 'Gizlin faýllary görkez', 'hide_hidden': 'Gizlin faýllary gizle', 'settings': 'Sazlamalar', 'theme': 'Tema', 'language': 'Dil', 'empty': 'Boş bukja', 'type': 'Görnüşi:', 'edit_dates': 'Seneleri redaktirle', 'save': 'Ýatda sakla', 'cancel': 'Ýatyr', 'about': 'Barada', 'version': 'Wersiýa', 'author': 'Awtor', 'disclaimer': 'Bolşy ýaly berilýär, kepillik ýok.', 'auto_update': 'Sessiz awto täzelenme', 'check_update': 'Täzelenmeleri barla', 'update_found': 'Täzelenme bar', 'theme_title': 'Temalar', 'mode_light': 'Yşykly', 'mode_dark': 'Garaňky', 'mode_oled': 'OLED gara', 'custom_themes': 'Özel temalar', 'theme_name': 'Tema ady', 'create': 'Döret', 'delete': 'Poz', 'otken_title': 'Ötken — Wersiýa taryhy', 'no_snapshots': 'Snapshot tapylmady', 'office_wait': 'LibreOffice öwürmesi…', 'office_missing': 'LibreOffice ýok: önükleme ýok', 'language_title': 'Dil', 'created_note': 'Linux-da bellip bolmaýar (ýadro çäklendirmesi). Windows-da redaktirlenýär.', 'open': 'Aç', 'copy': 'Göçür', 'cut': 'Kes', 'paste': 'Ýapyşdyr', 'rename': 'Adyny üýtget', 'batch_rename': 'Toplaýyn adyny üýtgetme', 'properties': 'Aýratynlyklar', 'new_folder': 'Täze bukja', 'confirm_delete': 'Pozmany tassykla', 'confirm_delete_msg': 'Bu elementi hakykatdan pozmak isleýärsiňizmi?', 'folder_name': 'Bukja ady', 'sort_name': 'Ad', 'sort_size': 'Möçber', 'sort_date': 'Sene', 'refresh': 'Täzele', 'batch_mode_number': 'Belgileme (esas + belgi)', 'batch_mode_replace': 'Tap / çalşyr', 'batch_mode_case': 'Harp ölçegi', 'batch_base': 'Esas ad', 'batch_start': 'Başlangyç belgi', 'batch_search': 'Tap', 'batch_replace': 'Çalşyr', 'batch_lower': 'kiçi harplar', 'batch_upper': 'ULY HARPLAR', 'batch_preview': 'Täze atlaryň önükleme'},
    'ky': {'title': 'Körün — Файл менеджери', 'select_file': 'Көрүү үчүн файл тандаңыз', 'details': 'Файлдын чоо-жайы', 'name': 'Аты:', 'path': 'Жол:', 'size': 'Өлчөмү:', 'modified': 'Өзгөртүлгөн:', 'accessed': 'Кайрылган:', 'created': 'Түзүлгөн:', 'left_panel': 'Сол панель', 'right_panel': 'Оң панель', 'preview': 'Көрүү', 'show_hidden': 'Жашыруун файлдарды көрсөтүү', 'hide_hidden': 'Жашыруун файлдарды жашыруу', 'settings': 'Жөндөөлөр', 'theme': 'Тема', 'language': 'Тил', 'empty': 'Бош папка', 'type': 'Түрү:', 'edit_dates': 'Күндөрдү түзөтүү', 'save': 'Сактоо', 'cancel': 'Жокко чыгаруу', 'about': 'Жөнүндө', 'version': 'Версия', 'author': 'Автор', 'disclaimer': 'Кандай болсо ошондой берилет, кепилдик жок.', 'auto_update': 'Үнсүз авто жаңыртуу', 'check_update': 'Жаңыртууларды текшерүү', 'update_found': 'Жаңыртуу бар', 'theme_title': 'Темалар', 'mode_light': 'Жарык', 'mode_dark': 'Караңгы', 'mode_oled': 'OLED кара', 'custom_themes': 'Өзгөчө темалар', 'theme_name': 'Тема аты', 'create': 'Жаратуу', 'delete': 'Өчүрүү', 'otken_title': 'Ötken — Версиялар тарыхы', 'no_snapshots': 'Snapshot табылган жок', 'office_wait': 'LibreOffice конвертациясы…', 'office_missing': 'LibreOffice жок: көрүү жок', 'language_title': 'Тил', 'created_note': 'Linux-та орнотулбайт (ядро чектөөсү). Windows-та түзөтүлөт.', 'open': 'Ачуу', 'copy': 'Көчүрүү', 'cut': 'Кесүү', 'paste': 'Коюу', 'rename': 'Атын өзгөртүү', 'batch_rename': 'Топтук ат өзгөртүү', 'properties': 'Касиеттери', 'new_folder': 'Жаңы папка', 'confirm_delete': 'Өчүрүүнү ырастоо', 'confirm_delete_msg': 'Бул элементти чын эле өчүргүңүз келеби?', 'folder_name': 'Папка аты', 'sort_name': 'Ат', 'sort_size': 'Өлчөм', 'sort_date': 'Дата', 'refresh': 'Жаңыртуу', 'batch_mode_number': 'Номурлоо (негиз + номур)', 'batch_mode_replace': 'Табуу / алмаштыруу', 'batch_mode_case': 'Тамга өлчөмү', 'batch_base': 'Негиз ат', 'batch_start': 'Башталгыч номур', 'batch_search': 'Табуу', 'batch_replace': 'Алмаштыруу', 'batch_lower': 'кичүү тамгалар', 'batch_upper': 'ЧОҢ ТАМГАЛАР', 'batch_preview': 'Жаңы аттарды алдын ала көрүү'},
    'tt': {'title': 'Körün — Файл менеджеры', 'select_file': 'Карау өчен файл сайлагыз', 'details': 'Файл детальләре', 'name': 'Исем:', 'path': 'Юл:', 'size': 'Күләм:', 'modified': 'Үзгәртелгән:', 'accessed': 'Мөрәҗәгать:', 'created': 'Ясалган:', 'left_panel': 'Сул панель', 'right_panel': 'Уң панель', 'preview': 'Карау', 'show_hidden': 'Яшерен файлларны күрсәтү', 'hide_hidden': 'Яшерен файлларны яшерү', 'settings': 'Көйләүләр', 'theme': 'Тема', 'language': 'Тел', 'empty': 'Буш папка', 'type': 'Төр:', 'edit_dates': 'Көннәрне үзгәртү', 'save': 'Саклау', 'cancel': 'Баш тарту', 'about': 'Турында', 'version': 'Версия', 'author': 'Автор', 'disclaimer': 'Ничек бар шулай бирелә, гарантия юк.', 'auto_update': 'Тавышсыз авто яңарту', 'check_update': 'Яңартуларны тикшерү', 'update_found': 'Яңарту бар', 'theme_title': 'Темалар', 'mode_light': 'Ачык', 'mode_dark': 'Карангы', 'mode_oled': 'OLED кара', 'custom_themes': 'Үз темалары', 'theme_name': 'Тема исеме', 'create': 'Ясау', 'delete': 'Бетерү', 'otken_title': 'Ötken — Версияләр тарихы', 'no_snapshots': 'Snapshot табылмады', 'office_wait': 'LibreOffice әверелдерү…', 'office_missing': 'LibreOffice юк: карау юк', 'language_title': 'Тел', 'created_note': 'Linux-та билгеләнми (ядро чикләве). Windows-та үзгәртелә.', 'open': 'Ачу', 'copy': 'Күчерү', 'cut': 'Кисү', 'paste': 'Кую', 'rename': 'Исемне үзгәртү', 'batch_rename': 'Төркемләп исем үзгәртү', 'properties': 'Үзлекләре', 'new_folder': 'Яңа папка', 'confirm_delete': 'Бетерүне раслау', 'confirm_delete_msg': 'Бу элементны чыннан бетерергә телисезме?', 'folder_name': 'Папка исеме', 'sort_name': 'Исем', 'sort_size': 'Күләм', 'sort_date': 'Дата', 'refresh': 'Яңарту', 'batch_mode_number': 'Санлау (нигез + сан)', 'batch_mode_replace': 'Табу / алыштыру', 'batch_mode_case': 'Хәреф үлчәме', 'batch_base': 'Нигез исем', 'batch_start': 'Башлангыч сан', 'batch_search': 'Табу', 'batch_replace': 'Алыштыру', 'batch_lower': 'кече хәрефләр', 'batch_upper': 'ЗУР ХӘРЕФЛӘР', 'batch_preview': 'Яңа исемнәрне алдан карау'},
  };

  static const Map<String, Map<String, String>> _extraValues = {
    'fr': {
      'show_previews': 'Afficher les aperçus dans les deux panneaux',
      'open_with': 'Ouvrir avec…',
      'open_with_failed': 'Impossible d’ouvrir le sélecteur « Ouvrir avec »',
      'no_open_with_apps': 'Aucune application installée ne reconnaît ce type de fichier.',
      'compress': 'Compresser en ZIP…',
      'archive_name': 'Nom de l’archive',
      'extract_here': 'Extraire ici',
      'archive_created': 'Archive créée',
      'archive_extracted': 'Archive extraite dans',
      'operation_failed': 'Échec de l’opération',
      'video_preview_unavailable':
          'Miniature indisponible. Installez ffmpeg pour créer un aperçu.',
      'audio_preview_unavailable':
          'Pochette indisponible. Installez ffmpeg pour afficher l’aperçu.',
      'legal_information': 'Licences et informations légales',
      'third_party_licenses': 'Licences des dépendances',
      'app_license': 'Körün est distribué sous licence MIT. Le texte intégral figure dans le fichier LICENSE du dépôt.',
    },
    'en': {
      'show_previews': 'Show previews in both panes',
      'open_with': 'Open with…',
      'open_with_failed': 'Could not open the “Open with” chooser',
      'no_open_with_apps': 'No installed application recognizes this file type.',
      'compress': 'Compress to ZIP…',
      'archive_name': 'Archive name',
      'extract_here': 'Extract here',
      'archive_created': 'Archive created',
      'archive_extracted': 'Archive extracted to',
      'operation_failed': 'Operation failed',
      'video_preview_unavailable':
          'Thumbnail unavailable. Install ffmpeg to generate a preview.',
      'audio_preview_unavailable':
          'Cover unavailable. Install ffmpeg to show this preview.',
      'legal_information': 'Licenses and legal information',
      'third_party_licenses': 'Third-party dependency licenses',
      'app_license': 'Körün is distributed under the MIT License. The full text is in the repository LICENSE file.',
    },
    'tr': {
      'show_previews': 'Her iki panelde de önizlemeleri göster',
      'open_with': 'Birlikte aç…',
      'open_with_failed': '“Birlikte aç” seçicisi açılamadı',
      'no_open_with_apps': 'Bu dosya türünü tanıyan yüklü bir uygulama yok.',
      'compress': 'ZIP olarak sıkıştır…',
      'archive_name': 'Arşiv adı',
      'extract_here': 'Buraya çıkar',
      'archive_created': 'Arşiv oluşturuldu',
      'archive_extracted': 'Arşiv çıkarıldı:',
      'operation_failed': 'İşlem başarısız',
      'video_preview_unavailable':
          'Küçük resim kullanılamıyor. Önizleme oluşturmak için ffmpeg yükleyin.',
      'audio_preview_unavailable':
          'Kapak kullanılamıyor. Önizlemeyi göstermek için ffmpeg yükleyin.',
      'legal_information': 'Lisanslar ve yasal bilgiler',
      'third_party_licenses': 'Üçüncü taraf bağımlılık lisansları',
      'app_license': 'Körün MIT Lisansı ile dağıtılır. Lisansın tam metni depodaki LICENSE dosyasındadır.',
    },
  };

  static String t(Locale locale, String key) =>
      _values[locale.languageCode]?[key] ??
      _extraValues[locale.languageCode]?[key] ??
      _values['en']![key] ??
      _extraValues['en']![key] ??
      key;
}

String tr(BuildContext context, String key) =>
    L10n.t(Localizations.localeOf(context), key);
